x-autoware-base: &autoware-base
  image: "aichallenge-2025-dev"
  privileged: true
  pull_policy: never
  network_mode: host
  stop_grace_period: 0.1s
  environment:
    - DISPLAY=${DISPLAY}
    - USER=${USER}
    - ROS_DISTRO=humble
    - XAUTHORITY=${XAUTHORITY}
    - QT_X11_NO_MITSHM=1
    - TZ=Asia/Tokyo
    - RUN_MODE=${RUN_MODE:-}
    - SIM_MODE=${SIM_MODE:-}
    - CMD=${CMD:-}
    - COLCON_TRACE=${COLCON_TRACE:-}
    - AIC_CAPTURE=${AIC_CAPTURE:-false}
    - AIC_ROSBAG=${AIC_ROSBAG:-false}
    - ROS_HOME=${ROS_HOME:-}
    - ROS_LOG_DIR=${ROS_LOG_DIR:-}
  volumes:
    - ./output:${OUTPUT_ROOT:-/output}
    - ./aichallenge:/aichallenge
    - ./remote:/remote
    - ./vehicle:/vehicle
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    # Audio (PipeWire/Pulse) socket access on the host
    - /run/user:/run/user:rw
    - /dev/dri:/dev/dri
    - ${XAUTHORITY}:${XAUTHORITY}:rw
  devices:
    - /dev/dri
    - /dev/video0
    - /dev/input
  working_dir: ${LOG_DIR:-/aichallenge}

x-racing_kart_interface-base: &racing_kart_interface-base
  image: "ghcr.io/tier4/racing_kart_interface:latest-experiment"
  privileged: true
  pull_policy: never
  network_mode: host
  stop_grace_period: 0.1s
  environment:
    - DISPLAY=${DISPLAY}
    - USER=${USER}
    - TZ=Asia/Tokyo
    - ROS_DISTRO=humble
    - NTRIP_USERNAME=${NTRIP_USERNAME:-}
    - NTRIP_PASSWORD=${NTRIP_PASSWORD:-}
  volumes:
    - /dev/vcu:/dev/vcu
    - /dev/gnss:/dev/gnss
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /dev/dri:/dev/dri
  devices:
    - /dev/dri
  group_add:
    - dialout
  working_dir: /workspace

services:
  # Autoware service
  autoware:
    <<: *autoware-base
    command: ["bash", "-lc", "exec /aichallenge/run_autoware.bash ${RUN_MODE:-awsim} ${DOMAIN_ID:-1} >\"${LOG_DIR:-/output}/autoware.log\" 2>&1"]

  # Autoware service
  autoware-build:
    <<: *autoware-base 
    command: ["bash", "-lc", "exec bash /aichallenge/build_autoware.bash ${HOST_UID:-} ${HOST_GID:-}"]

  simulator:
    <<: *autoware-base 
    command: ["bash", "-lc", "exec env PULSE_SERVER=unix:/run/user/${HOST_UID:-1000}/pulse/native /aichallenge/run_simulator.bash ${SIM_MODE:-} >\"${LOG_DIR:-/output}/awsim.log\" 2>&1"]

  autoware-command:
    <<: *autoware-base
    command: ["bash", "-lc", "source /aichallenge/workspace/install/setup.bash && cd ${CMD_WORKDIR:-/aichallenge} && exec bash -lc \"${CMD:-}\""]

  autoware-simulator-evaluation:
    <<: *autoware-base 
    command: ["bash", "-lc", "exec /aichallenge/run_evaluation.bash"]

### Autoware Service For Parallel Execution ###
  autoware-d1:
    <<: *autoware-base 
    image: "autoware-d1"
    command: ["bash", "-lc", "source /aichallenge/workspace/install/setup.bash && exec env ROS_DOMAIN_ID=1 ros2 launch aichallenge_system_launch aichallenge_system.launch.xml simulation:=true use_sim_time:=true run_rviz:=true domain_id:=1 > \"${LOG_DIR:-/output}/autoware.log\" 2>&1"]

  autoware-d2:
    <<: *autoware-base 
    image: "autoware-d2"
    command: ["bash", "-lc", "source /aichallenge/workspace/install/setup.bash && exec env ROS_DOMAIN_ID=2 ros2 launch aichallenge_system_launch aichallenge_system.launch.xml simulation:=true use_sim_time:=true run_rviz:=true domain_id:=2 > \"${LOG_DIR:-/output}/autoware.log\" 2>&1"]

  autoware-d3:
    <<: *autoware-base
    image: "autoware-d3"
    command: ["bash", "-lc", "source /aichallenge/workspace/install/setup.bash && exec env ROS_DOMAIN_ID=3 ros2 launch aichallenge_system_launch aichallenge_system.launch.xml simulation:=true use_sim_time:=true run_rviz:=true domain_id:=3 > \"${LOG_DIR:-/output}/autoware.log\" 2>&1"]

  autoware-d4:
    <<: *autoware-base
    image: "autoware-d4"
    command: ["bash", "-lc", "source /aichallenge/workspace/install/setup.bash && exec env ROS_DOMAIN_ID=4 ros2 launch aichallenge_system_launch aichallenge_system.launch.xml simulation:=true use_sim_time:=true run_rviz:=true domain_id:=4 > \"${LOG_DIR:-/output}/autoware.log\" 2>&1"]

#### vehicle specific services can be added here ####
  # Zenoh service
  zenoh:
    <<: *autoware-base
    working_dir: /vehicle
    command: ["bash", "-c", "case ${VEHICLE_ID:-} in A2) PORT=7448;; A3) PORT=7449;; A6) PORT=7450;; A7) PORT=7451;; *) echo 'Invalid VEHICLE_ID'; exit 1;; esac && zenoh-bridge-ros2dds client -e tls/zenoh.dev.aichallenge-board.jsae.or.jp:$$PORT -c /vehicle/zenoh.json5"]

  # Driver service
  driver:
    <<: *racing_kart_interface-base
    command: ['vehicle']

#### remote visualization services ####
  rviz2:
    <<: *autoware-base 
    command: ["bash", "-c", "cd /aichallenge && exec bash utils/run_rviz.bash remote"]
