/**:
  ros__parameters:
    log_interval_sec: 5.0

    model:
      image_height: 66
      image_width: 200
      output_dim: 2
      color_space: "yuv"        # "rgb" or "yuv"
      crop_top_ratio: 0.375     # fraction of height to crop from top
      crop_bottom_ratio: 0.0    # fraction of height to crop from bottom
      ckpt_path: ""

    control_mode: "ai"
    acceleration: 0.6

    debug: false
