#!/usr/bin/env python3
import argparse
import time
from pathlib import Path

import rclpy
from rclpy.node import Node
from std_msgs.msg import String


def parse_simple_yaml(path: Path) -> dict:
    data: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if not value:
            continue
        if value[0] in ("'", '"') and value[-1] == value[0]:
            value = value[1:-1]
        else:
            value = value.split("#", 1)[0].strip()
        data[key] = value
    return data


def render_qss(vars_: dict) -> str:
    bg = vars_.get("background", "#1b1026")
    surface2 = vars_.get("surface2", "#3a1659")
    pink = vars_.get("pink", "#ff69b4")
    purple = vars_.get("purple", "#ba68c8")
    text = vars_.get("text", "#ffe7ff")
    font_size = vars_.get("font_size", "12px")

    return f"""/* Generated by cute_theme_watch.py */
QWidget {{
  background-color: {bg};
  color: {text};
  font-size: {font_size};
}}

QMainWindow, QDockWidget {{
  background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 {surface2}, stop:1 {bg});
}}

QLineEdit {{
  padding: 7px 10px;
  border-radius: 12px;
  border: 1px solid rgba(255, 105, 180, 0.45);
  background-color: rgba(255, 255, 255, 0.06);
  selection-background-color: rgba(186, 104, 200, 0.55);
}}

QPushButton {{
  padding: 7px 12px;
  border-radius: 14px;
  border: 1px solid rgba(255, 105, 180, 0.50);
  background-color: rgba(255, 105, 180, 0.18);
}}
QPushButton:hover {{
  background-color: rgba(186, 104, 200, 0.24);
  border: 1px solid rgba(186, 104, 200, 0.55);
}}

QCheckBox::indicator:checked {{
  background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255,105,180,0.75), stop:1 rgba(186,104,200,0.75));
}}

QLabel#CuteTitleLabel {{
  font-size: 16px;
  font-weight: 700;
  padding: 8px 10px;
  border-radius: 10px;
  background-color: rgba(255, 105, 180, 0.18);
  border: 1px solid rgba(255, 105, 180, 0.45);
}}
"""


class ThemeWatchPublisher(Node):
    def __init__(self, topic: str, yaml_path: Path):
        super().__init__("cute_theme_watch_publisher")
        self.pub = self.create_publisher(String, topic, 1)
        self.topic = topic
        self.yaml_path = yaml_path
        self.last_mtime_ns: int | None = None
        self.last_bytes: bytes | None = None

    def tick(self):
        try:
            stat = self.yaml_path.stat()
        except FileNotFoundError:
            self.get_logger().warn(f"YAML not found: {self.yaml_path}")
            return

        if self.last_mtime_ns == stat.st_mtime_ns:
            return

        raw = self.yaml_path.read_bytes()
        if self.last_bytes == raw:
            self.last_mtime_ns = stat.st_mtime_ns
            return

        vars_ = parse_simple_yaml(self.yaml_path)
        qss = render_qss(vars_)
        msg = String()
        msg.data = qss
        self.pub.publish(msg)

        self.last_mtime_ns = stat.st_mtime_ns
        self.last_bytes = raw
        self.get_logger().info(f"Published updated theme to {self.topic} ({len(qss)} bytes)")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--yaml", required=True, help="Path to simple theme yaml")
    ap.add_argument("--topic", default="/cute_style_rviz_plugin/theme_qss")
    ap.add_argument("--rate", type=float, default=2.0, help="Poll rate (Hz)")
    args = ap.parse_args()

    yaml_path = Path(args.yaml)
    if args.rate <= 0:
        ap.error("--rate must be > 0")

    rclpy.init()
    node = ThemeWatchPublisher(args.topic, yaml_path)

    period = 1.0 / args.rate
    try:
        while rclpy.ok():
            node.tick()
            rclpy.spin_once(node, timeout_sec=0.0)
            time.sleep(period)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
