#!/usr/bin/env python3
import argparse
import sys
from pathlib import Path


def parse_simple_yaml(path: Path) -> dict:
    data: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if not value:
            continue
        if value[0] in ("'", '"') and value[-1] == value[0]:
            value = value[1:-1]
        else:
            value = value.split("#", 1)[0].strip()
        data[key] = value
    return data


def render_qss(vars_: dict) -> str:
    bg = vars_.get("background", "#1b1026")
    surface = vars_.get("surface", "#2a1140")
    surface2 = vars_.get("surface2", "#3a1659")
    pink = vars_.get("pink", "#ff69b4")
    purple = vars_.get("purple", "#ba68c8")
    text = vars_.get("text", "#ffe7ff")
    font_size = vars_.get("font_size", "12px")

    return f"""/* Generated by cute_theme_generate.py */
QWidget {{
  background-color: {bg};
  color: {text};
  font-size: {font_size};
}}

QMainWindow, QDockWidget {{
  background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 {surface2}, stop:1 {bg});
}}

QLineEdit {{
  padding: 7px 10px;
  border-radius: 12px;
  border: 1px solid rgba(255, 105, 180, 0.45);
  background-color: rgba(255, 255, 255, 0.06);
}}

QPushButton {{
  padding: 7px 12px;
  border-radius: 14px;
  border: 1px solid rgba(255, 105, 180, 0.50);
  background-color: rgba(255, 105, 180, 0.18);
}}
QPushButton:hover {{
  background-color: rgba(186, 104, 200, 0.24);
}}

QLabel#CuteTitleLabel {{
  font-size: 16px;
  font-weight: 700;
  padding: 8px 10px;
  border-radius: 10px;
  background-color: rgba(255, 105, 180, 0.18);
  border: 1px solid rgba(255, 105, 180, 0.45);
}}
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--yaml", required=True, help="Path to simple theme yaml")
    ap.add_argument("--out", default="-", help="Output .qss path (or - for stdout)")
    ap.add_argument(
        "--set",
        action="append",
        default=[],
        help="Override variables (KEY=VALUE). Can be specified multiple times.",
    )
    args = ap.parse_args()

    vars_ = parse_simple_yaml(Path(args.yaml))
    for item in args.set:
        if "=" not in item:
            ap.error(f"--set must be KEY=VALUE (got: {item})")
        k, v = item.split("=", 1)
        vars_[k.strip()] = v.strip()
    qss = render_qss(vars_)

    if args.out == "-":
        sys.stdout.write(qss)
        return 0
    Path(args.out).write_text(qss, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
